#!/bin/sh
#fake service to permit glass to restart the dhcp server
case "$2" in
  start) 
    /etc/rc.d/init.d/isc-dhcpd.service start
    ;;
  stop)
    /etc/rc.d/init.d/isc-dhcpd.service stop
    ;;
  restart)
    /etc/rc.d/init.d/isc-dhcpd.service stop
    /etc/rc.d/init.d/isc-dhcpd.service start
    ;;
  *)      
    printf "Invalid command - Valid->start|stop|restart\n"
    ;;
esac
